/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the Apache License, Version 2.0.
 */

import type { StorageConnectionParams, GeneratedScript } from '../../types/storage-connection-types';

/**
 * Generates Azure CLI commands for connecting a storage account
 * to the CCF Ledger Explorer managed application.
 *
 * The user copies these commands and runs them in their own terminal
 * with an authenticated `az` session. No secrets or tokens are stored
 * in the browser.
 */
export function generateCliScripts(params: StorageConnectionParams): GeneratedScript[] {
  const {
    subscriptionId,
    storageResourceGroup,
    storageAccountName,
    location,
    topicName,
    subscriptionName,
    managedResourceGroup,
    serviceBusNamespace,
    serviceBusQueueName,
    functionIdentityOid,
    sessionId,
    includeDeleteEvents,
  } = params;

  const storageAccountResourceId =
    `/subscriptions/${subscriptionId}/resourceGroups/${storageResourceGroup}/providers/Microsoft.Storage/storageAccounts/${storageAccountName}`;

  const serviceBusQueueResourceId =
    `/subscriptions/${subscriptionId}/resourceGroups/${managedResourceGroup}/providers/Microsoft.ServiceBus/namespaces/${serviceBusNamespace}/queues/${serviceBusQueueName}`;

  const eventTypes = includeDeleteEvents
    ? 'Microsoft.Storage.BlobCreated Microsoft.Storage.BlobDeleted'
    : 'Microsoft.Storage.BlobCreated';

  const scripts: GeneratedScript[] = [
    {
      label: 'Step 1: Create Event Grid System Topic',
      description:
        'Creates an Event Grid system topic on the storage account to capture blob events. ' +
        'A system-assigned managed identity is enabled so the topic can forward events to Service Bus.',
      command: `az eventgrid system-topic create \\
  --resource-group "${storageResourceGroup}" \\
  --name "${topicName}" \\
  --location "${location}" \\
  --topic-type microsoft.storage.storageaccounts \\
  --source "${storageAccountResourceId}" \\
  --identity SystemAssigned`,
    },
    {
      label: 'Step 2: Assign Service Bus Data Sender to the System Topic',
      description:
        "Grants the system topic's managed identity the 'Azure Service Bus Data Sender' role " +
        'on the Service Bus queue so it can deliver events.',
      command: `# First, get the system topic's principal ID:
TOPIC_PRINCIPAL_ID=$(az eventgrid system-topic show \\
  --resource-group "${storageResourceGroup}" \\
  --name "${topicName}" \\
  --query "identity.principalId" -o tsv)

# Then assign the role:
az role assignment create \\
  --role "Azure Service Bus Data Sender" \\
  --assignee-object-id "$TOPIC_PRINCIPAL_ID" \\
  --assignee-principal-type ServicePrincipal \\
  --scope "${serviceBusQueueResourceId}"`,
    },
    {
      label: 'Step 3: Create Event Subscription',
      description:
        'Creates an event subscription that forwards blob events from the storage account ' +
        'to the Service Bus queue used by the managed application.',
      command: `az eventgrid system-topic event-subscription create \\
  --name "${subscriptionName}" \\
  --system-topic-name "${topicName}" \\
  --resource-group "${storageResourceGroup}" \\
  --event-delivery-schema EventGridSchema \\
  --included-event-types ${eventTypes} \\
  --delivery-attribute-mapping sessionId static "${sessionId}" false \\
  --delivery-identity-endpoint-type servicebusqueue \\
  --delivery-identity systemassigned \\
  --delivery-identity-endpoint "${serviceBusQueueResourceId}"`,
    },
    {
      label: 'Step 4: Assign Storage Blob Data Owner to the Function Identity',
      description:
        "Grants the managed application's Azure Function the 'Storage Blob Data Owner' role " +
        'on the storage account so it can read blobs and compute digests.',
      command: `az role assignment create \\
  --role "Storage Blob Data Owner" \\
  --assignee-object-id "${functionIdentityOid}" \\
  --assignee-principal-type ServicePrincipal \\
  --scope "${storageAccountResourceId}"`,
    },
  ];

  return scripts;
}

/**
 * Combines all generated CLI scripts into a single copyable shell script.
 */
export function generateFullScript(params: StorageConnectionParams): string {
  const scripts = generateCliScripts(params);
  const header = `#!/bin/bash
# =============================================================================
# Connect Storage Account to CCF Ledger Explorer Managed Application
# Generated by CCF Ledger Explorer on ${new Date().toISOString()}
#
# Prerequisites:
#   - Azure CLI installed and authenticated (az login)
#   - Sufficient permissions (Owner or Contributor + User Access Administrator)
#     on the storage account resource group
#   - Reader access on the managed resource group
#
# Storage Account: ${params.storageAccountName}
# Subscription:    ${params.subscriptionId}
# =============================================================================

set -euo pipefail

`;

  const body = scripts
    .map((s) => `# ${s.label}\n# ${s.description}\n${s.command}\n`)
    .join('\necho "---"\n\n');

  return header + body + '\necho "Done. Storage account connected successfully."\n';
}
