name: Build
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build-ts-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: npm ci
        name: Install dependencies
      - run: npm run lint
        name: Run linter
      - run: npm run build
        name: Build app
      - run: npm test
        name: Run tests